# Generated by Django 4.2.9 on 2024-08-02 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_chat', models.IntegerField(unique=True)),
                ('first_user', models.IntegerField()),
                ('second_user', models.IntegerField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'chat',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_message', models.IntegerField(unique=True)),
                ('text', models.CharField(max_length=255)),
                ('id_sender', models.GenericIPAddressField()),
                ('id_recipient', models.IntegerField()),
                ('message_isread', models.BooleanField()),
                ('time_send_message', models.DateTimeField(auto_now_add=True)),
                ('id_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.chat')),
            ],
            options={
                'verbose_name': 'message',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
            },
        ),
    ]
