# Generated by Django 4.2.9 on 2024-08-04 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logic', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id_chat', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('first_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_created', to=settings.AUTH_USER_MODEL)),
                ('second_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'chat',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id_message', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('text', models.CharField(max_length=255)),
                ('ip_sender', models.GenericIPAddressField()),
                ('time_send_message', models.DateTimeField(auto_now_add=True)),
                ('id_chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logic.chat')),
                ('id_recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('id_sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'message',
            },
        ),
    ]
